### ISSUE TITLE
My `docker-compose.yml` config / How to run bbctl in Docker compose

### ISSUE THREAD

**Issue by devnoname120** [beeper/bridge-manager#51]
Create a file `docker-compose.yml` or `compose.yml`:

```yaml
x-bbctl-template: &bbctl
  image: ghcr.io/beeper/bridge-manager:latest
  restart: unless-stopped
  entrypoint: ['/usr/local/bin/bbctl', 'run', '--no-override-config']
  volumes:
    - ./data:/data
  environment:
    MATRIX_ACCESS_TOKEN: ${MATRIX_ACCESS_TOKEN}
    BBCTL_CONFIG: /data/bbctl.json
    BEEPER_ENV: prod
    DATA_DIR: /data
    DB_DIR: /data/db
  env_file:
    - .env
 
services:
  signal:
    <<: *bbctl
    command: sh-mautrix-signal
  instagram:
    <<: *bbctl
    command: sh-mautrix-instagram
  facebook:
    <<: *bbctl
    command: sh-mautrix-facebook
  whatsapp:
    <<: *bbctl
    command: sh-mautrix-whatsapp
  telegram:
    <<: *bbctl
    command: sh-mautrix-telegram
  linkedin:
    <<: *bbctl
    command: sh-mautrix-linkedin
  twitter:
    <<: *bbctl
    command: sh-mautrix-twitter
  discord:
    <<: *bbctl
    command: sh-mautrix-discord
  slack:
    <<: *bbctl
    command: sh-mautrix-slack
```

Then in the same directory create a `.env` file and put your Matrix token inside:

```
MATRIX_ACCESS_TOKEN=syt_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

You can then start the containers:

```shell
docker compose up --detach
```

**Note**: If you need to manually run a `bbctl` command you can always do something like this (here it's for logging in Beeper):

```shell
docker run --rm -it -v ./data:/data --env-file .env -e "BBCTL_CONFIG=/data/bbctl.json" -e "BEEPER_ENV=prod" -e "DATA_DIR=/data" -e "DB_DIR=/data/db" --entrypoint bbctl ghcr.io/beeper/bridge-manager:latest login-password

```
